{{- if .Values.coreServices.llamaServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digitnxt.fullname" . }}-llama
  labels:
    {{- include "digitnxt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.coreServices.llamaServer.replicas }}
  selector:
    matchLabels:
      {{- include "digitnxt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: llama
  template:
    metadata:
      labels:
        {{- include "digitnxt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: llama
    spec:
      serviceAccountName: {{ include "digitnxt.serviceAccountName" . }}
      containers:
        - name: llama
          image: "{{ .Values.coreServices.llamaServer.image.repository }}:{{ .Values.coreServices.llamaServer.image.tag }}"
          imagePullPolicy: {{ .Values.coreServices.llamaServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.coreServices.llamaServer.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.coreServices.llamaServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: CONSUL_HOST
              value: "consul-server"
            - name: CONSUL_PORT
              value: "8500"
            - name: SERVICE_NAME
              value: "llama-server"
            - name: MODEL_PATH
              value: "/models"
          volumeMounts:
            - name: model-storage
              mountPath: /models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: {{ include "digitnxt.pvcName" . }}-models
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "digitnxt.fullname" . }}-llama
  labels:
    {{- include "digitnxt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coreServices.llamaServer.service.type }}
  ports:
    - port: {{ .Values.coreServices.llamaServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "digitnxt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llama
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "digitnxt.pvcName" . }}-models
  labels:
    {{- include "digitnxt.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.coreServices.llamaServer.persistence.size }}
  storageClassName: {{ .Values.global.storageClass }}
{{- end }} 