{{- if .Values.coreServices.llmClient.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "digitnxt.fullname" . }}-llm-client
  labels:
    {{- include "digitnxt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.coreServices.llmClient.replicas }}
  selector:
    matchLabels:
      {{- include "digitnxt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: llm-client
  template:
    metadata:
      labels:
        {{- include "digitnxt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: llm-client
    spec:
      serviceAccountName: {{ include "digitnxt.serviceAccountName" . }}
      containers:
        - name: llm-client
          image: "{{ .Values.coreServices.llmClient.image.repository }}:{{ .Values.coreServices.llmClient.image.tag }}"
          imagePullPolicy: {{ .Values.coreServices.llmClient.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.coreServices.llmClient.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.coreServices.llmClient.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: CONSUL_HOST
              value: "consul-server"
            - name: CONSUL_PORT
              value: "8500"
            - name: SERVICE_NAME
              value: "llm-client"
            - name: MCP_SERVICE_URL
              value: "http://{{ include "digitnxt.fullname" . }}-mcp:{{ .Values.coreServices.mcpService.service.port }}"
            - name: LLAMA_SERVER_URL
              value: "http://{{ include "digitnxt.fullname" . }}-llama:{{ .Values.coreServices.llamaServer.service.port }}"
            - name: IDENTITY_SERVICE_URL
              value: "http://{{ include "digitnxt.fullname" . }}-identity:{{ .Values.coreServices.identity.service.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "digitnxt.fullname" . }}-llm-client
  labels:
    {{- include "digitnxt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coreServices.llmClient.service.type }}
  ports:
    - port: {{ .Values.coreServices.llmClient.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "digitnxt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llm-client
{{- end }} 