{{- if .Values.networkSecurity.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "digitnxt.fullname" . }}-security
  labels:
    {{- include "digitnxt.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "digitnxt.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkSecurity.ingressRules }}
    - from:
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
            {{- if .ipBlock.except }}
            except:
              {{- toYaml .ipBlock.except | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector.matchLabels | nindent 14 }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  egress:
    {{- range .Values.networkSecurity.egressRules }}
    - to:
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr }}
            {{- if .ipBlock.except }}
            except:
              {{- toYaml .ipBlock.except | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector.matchLabels | nindent 14 }}
        {{- end }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
{{- end }} 