basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for exposing OpenAPI with Gin and Swaggo
  title: Example API
  version: "1.0"
paths:
  /ping:
    get:
      description: Returns a pong message
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping the server
      tags:
      - health
swagger: "2.0"
