apiVersion: v2
name: digitnxt
description: A Helm chart for DigitNxt platform deployment
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: "22.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
  - name: redis
    version: "17.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kong
    version: "2.8.0"
    repository: "https://charts.konghq.com"
    condition: kong.enabled
  - name: keycloak
    version: "15.0.0"
    repository: "https://codecentric.github.io/helm-charts"
    condition: keycloak.enabled
  - name: jaeger
    version: "0.69.0"
    repository: "https://jaegertracing.github.io/helm-charts"
    condition: jaeger.enabled
  - name: prometheus
    version: "19.7.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.56.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled 