apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
type: Opaque
stringData:
  password: kongpass
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  password: admin 