services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=registry
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Standard port: 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "registry"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  consul:
    image: hashicorp/consul:1.15
    ports:
      - "8500:8500"  # Standard port: 8500
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    networks:
      - app-network

  kong-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong", "-d", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  kong:
    build:
      context: ../../services/backbone/kong-synch
      dockerfile: Dockerfile.kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PG_PORT=5432
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_SERVICE_DISCOVERY=consul
      - KONG_CONSUL_HOST=consul
      - KONG_CONSUL_PORT=8500
      - KONG_NGINX_DAEMON=off 
    ports:
      - "8000:8000"
      - "8001:8001"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    depends_on:
      kong-db:
        condition: service_healthy
      consul:
        condition: service_started
    networks:
      - app-network

  kong-synch:  # Match logs naming
    build:
      context: ../../services/backbone/kong-synch
      dockerfile: Dockerfile
    command: "node synch.js"
    depends_on:
      kong:
        condition: service_healthy
      consul:
        condition: service_started
    networks:
      - app-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  kong-db-data:
    driver: local