basePath: /identity
host: localhost:8000
info:
  contact: {}
  description: This service handles identity and authentication related operations
  title: Identity Service API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Returns a simple pong response to verify the service is running
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
