{
 "title": "Kafka Exporter Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag",
     "legendFormat": "{{consumergroup}} | {{topic}} | {{partition}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partition Count Per Topic",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader{partition=\"0\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}