name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: llama-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: llama-deployment

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Configure Docker to use gcloud as a credential helper
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    # Build and push Docker images
    - name: Build and Push Docker Images
      run: |
        cd deployment/docker-compose
        docker-compose build
        docker-compose push

    # Get GKE credentials
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    # Deploy to GKE
    - name: Deploy to GKE
      run: |
        cd deployment/kubernetes/manifests
        kubectl apply -f .
        kubectl rollout status deployment/$DEPLOYMENT_NAME 